### PR TITLE
fix(script): wait for mount again

### LINKED ISSUE #342: TurnstileError: [Cloudflare Turnstile] Invalid type for parameter "container", expected "string" or an implementation of "HTMLElement".
### 🐛 The bug

Hello everyone, I apologize for the interruption.

I have a question: I encountered no issues using Turnstile in my frontend project.

However, when I use it on another page, I experience the following error during page transitions.

For instance, when both `app/pages/login.vue` and `app/pages/signup.vue` utilize the `NuxtTurnstile` component, the subsequent error arises. In the development environment, the page appears blank, while in the deployed version, the page displays correctly but fails to show the verification widget.

```
VM113320 api.js:1 Uncaught (in promise) TurnstileError: [Cloudflare Turnstile] Invalid type for parameter "container", expected "string" or an implementation of "HTMLElement".
```

image

### 🛠️ To reproduce

https://github.com/cdLab996/turnstile-examples-nuxt

### 🌈 Expected behaviour

It is anticipated to be displayed correctly across multiple pages.

image

### ℹ️ Additional context

_No response_

### PR DESCRIPTION
**Pull request by dargmuesli**
### 🔗 Linked issue

Resolves #342

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by danielroe — COMMENTED** [review]
is there a way we can add a regression test here? 🙏

**Comment by dargmuesli** [comment]
Should be possible by adding Turnstile to the subpage in the playground, but I'm currently too time limited to tinker with it. I haven't used Nuxt test utils before so it'd likely take me some time.

**Review by danielroe — APPROVED** [review]

**Review by danielroe — COMMENTED** [review]
or maybe we can start preloading when setup runs, and then not render until it's mounted ...

**Comment by huang-julien** [comment]
Just got the issue at work. This LGTM

**Comment by danielroe** [comment]
okay, let's merge and iterate 🙏

**Pull request merged**
