### PR TITLE
chore(component): remove `nextTick`

### PR DESCRIPTION
**Pull request by dargmuesli**
Both mentioned issues are resolved now.

### CODE REVIEW

**Comment by danielroe** [comment]
Nice! Have you confirmed that client-side navigation to a page with the Turnstile component still works?

**Comment by dargmuesli** [comment]
Yes, to the best of my knowledge: I enabled the playground widgets to load right away, navigated to `/home` and back and I noticed no issues.

**Comment by danielroe** [comment]
I think this is no longer relevant with Nuxt Scripts implementation

**Comment by dargmuesli** [comment]
Right, I think so too :rocket:

**Pull request closed without merging**
