### PR TITLE
chore: release v0.5.1

### PR DESCRIPTION
**Pull request by dargmuesli**
Proposed release for type fix included in https://github.com/nuxt-modules/turnstile/pull/263

### CODE REVIEW

**Comment by danielroe** [comment]
I don't believe any release is required as the only change was to this module's devDependencies:

https://github.com/nuxt-modules/turnstile/compare/v0.5.0...main

**Comment by danielroe** [comment]
Ahh - you mean you're getting a runtime error from type checking the Turnstile component?

**Comment by dargmuesli** [comment]
Yes, this is the fix I think to release: https://github.com/nuxt-modules/turnstile/compare/v0.5.0...main#diff-bc1c2b688c03023c444393cabce8b293da4e7cf5cdba97ef256748cdee6183f9R36

**Comment by dargmuesli** [comment]
Hmm, the link doesn't really point to the right tab when clicking on it. I mean the component file and the included type fix, which I squashed into the dev dependency update, so it doesn't show up as separate commit anymore.

**Comment by dargmuesli** [comment]
So it's not really a runtime error first for me, but a linting error downstream (https://github.com/maevsi/maevsi/pull/1347) that I think can only be resolved with an update to this package (and thus to the included component).

**Comment by danielroe** [comment]
Understood. I'll release a patch.

**Pull request closed without merging**
